#!/bin/bash --login
#PBS -N cp2k_1
#PBS -l select=8
#PBS -l walltime=08:00:00
#PBS -A z01-cse
#PBS -q short
#PBS -j oe

# Move to directory that script was submitted from
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR

export MPICH_VERSION_DISPLAY=1
export MPICH_ENV_DISPLAY=1
export MPICH_RANK_REORDER_DISPLAY=1
export MPICH_CPUMASK_DISPLAY=1

export OMP_NUM_THREADS=1
aprun -n 192 -N 24 -S 12 -d $OMP_NUM_THREADS -ss ./cp2k.psmp -i H2O-1024.inp >& stdouterr
